# -*- coding: utf-8 -*-
"""REG-ASI-F-10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VC49Eatsw6o6RXs-HOF1_xVs3dF1Zgsh
"""

from pyngrok import ngrok
ngrok.kill()

import sqlite3
import pandas as pd

# Cargar el Excel
df = pd.read_excel("trabajadores.xls")

# Crear base de datos
conn = sqlite3.connect("firmas.db")
cursor = conn.cursor()

# Crear tabla
cursor.execute("""
CREATE TABLE IF NOT EXISTS trabajadores (
    cedula TEXT PRIMARY KEY,
    nombre TEXT,
    cargo TEXT,
    firma TEXT
)
""")

# Insertar datos del Excel
for _, row in df.iterrows():
    cursor.execute("""
    INSERT OR REPLACE INTO trabajadores (cedula, nombre, cargo, firma)
    VALUES (?, ?, ?, NULL)
    """, (str(row["Cedula"]), row["Nombre"], row["Cargo"]))

conn.commit()
conn.close()

print("BASE DE DATOS CREADA CORRECTAMENTE")

# Conectarse a la base
conn = sqlite3.connect("firmas.db")

# Consulta: todas las columnas, 10 primeras filas
query = "SELECT * FROM trabajadores LIMIT 10"

df = pd.read_sql_query(query, conn)

df

from flask import Flask, request, send_file, render_template_string
from pyngrok import ngrok, conf
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas as pdfcanvas
from reportlab.lib.utils import ImageReader
import base64, sqlite3, os
from io import BytesIO
from datetime import datetime

# 🔑 TU TOKEN NGROK
conf.get_default().auth_token = "39Rcmwl3mT7TpTlx1OtwusqPdpV_3DjvrqxJpRnwEVWFrbNAt"

app = Flask(__name__)
DB_PATH = "firmas.db"

# ---------------- PAGINAS ----------------

pagina_login = """
<!doctype html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body { font-family: Arial, sans-serif; text-align: center; padding: 20px; }
    .logo { max-width: 180px; margin-bottom: 20px; }
    input, button { font-size: 18px; padding: 10px; width: 90%; max-width: 300px; }
    button { background: #ff7a00; color: white; border: none; border-radius: 5px; }
  </style>
</head>
<body>

  <img src="/logo" class="logo">

  <h2>Registro de Asistencia</h2>

  <form action="/buscar" method="post">
      <input type="text" name="cedula" placeholder="Ingrese su cédula" required>
      <br><br>
      <button type="submit">Continuar</button>
  </form>

  <br>
  <a href="/reporte_final" target="_blank">
    <button type="button">Generar PDF F-10</button>
  </a>

</body>
</html>
"""

pagina_gracias = """
<!doctype html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body {
      font-family: Arial, sans-serif;
      text-align: center;
      padding: 30px;
      background: #f7f7f7;
    }
    .logo { max-width: 180px; margin-bottom: 20px; }
    h2 { color: #1f4fa3; }
    button {
      background: #ff7a00;
      color: white;
      border: none;
      border-radius: 5px;
      padding: 12px 20px;
      font-size: 16px;
    }
  </style>
</head>
<body>

  <img src="/logo" class="logo">

  <h2>¡Gracias por registrar tu firma y proteger el medio ambiente!</h2>
  <p>Cero papel, tu firma fue guardada.</p>

  <button onclick="cerrar()">Finalizar</button>

  <script>
    function cerrar() {
      alert("Gracias ismocolit@ 🙌");
      window.close();
    }
  </script>

</body>
</html>
"""

firma_page = """
<!doctype html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body { font-family: Arial, sans-serif; text-align: center; padding: 20px; }
    canvas { border: 1px solid black; width: 350px; height: 200px; }
    button { background: #ff7a00; color: white; border: none; border-radius: 5px; padding: 10px 15px; margin: 5px; }
  </style>
</head>
<body>

  <img src="/logo" class="logo" style="max-width:120px;"><br>

  <h2>Firmar</h2>
  <b>Nombre:</b> {{nombre}}<br>
  <b>Cargo:</b> {{cargo}}<br><br>

  <canvas id="canvas"></canvas>
  <br><br>

  <button onclick="guardar()">Guardar Firma</button>
  <button onclick="limpiar()">Limpiar</button>

<script>
var canvas = document.getElementById("canvas");
var ctx = canvas.getContext("2d");
var dibujando = false;

function resizeCanvas() {
    var rect = canvas.getBoundingClientRect();
    canvas.width = rect.width;
    canvas.height = rect.height;
    ctx.lineWidth = 2;
    ctx.lineCap = "round";
}
resizeCanvas();
window.addEventListener("resize", resizeCanvas);

function getPos(e){
    var rect = canvas.getBoundingClientRect();
    if(e.touches){
        return {x: e.touches[0].clientX - rect.left, y: e.touches[0].clientY - rect.top};
    } else {
        return {x: e.offsetX, y: e.offsetY};
    }
}

canvas.addEventListener("mousedown", e => {dibujando=true; var p=getPos(e); ctx.beginPath(); ctx.moveTo(p.x,p.y);});
canvas.addEventListener("mousemove", e => {if(!dibujando) return; var p=getPos(e); ctx.lineTo(p.x,p.y); ctx.stroke();});
canvas.addEventListener("mouseup", ()=>dibujando=false);
canvas.addEventListener("mouseleave", ()=>dibujando=false);

canvas.addEventListener("touchstart", e => {e.preventDefault(); dibujando=true; var p=getPos(e); ctx.beginPath(); ctx.moveTo(p.x,p.y);});
canvas.addEventListener("touchmove", e => {e.preventDefault(); if(!dibujando) return; var p=getPos(e); ctx.lineTo(p.x,p.y); ctx.stroke();});
canvas.addEventListener("touchend", ()=>dibujando=false);

function limpiar(){ ctx.clearRect(0,0,canvas.width,canvas.height); }

function guardar(){
    var dataURL = canvas.toDataURL("image/png");
    fetch("/guardar", {
        method: "POST",
        headers: {"Content-Type":"application/x-www-form-urlencoded"},
        body: "firma=" + encodeURIComponent(dataURL) + "&cedula={{cedula}}"
    })
    .then(res => res.text())
    .then(html => {
        document.open();
        document.write(html);
        document.close();
    });
}
</script>

</body>
</html>
"""

# ---------------- RUTAS ----------------

@app.route("/")
def inicio():
    return pagina_login

@app.route("/logo") 
def logo(): return send_file("/content/Registro-de-asistencia-ISMOCOL-SA/logoismocol.png", mimetype="image/png")

@app.route("/buscar", methods=["POST"])
def buscar():
    cedula = request.form["cedula"]
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute("SELECT nombre, cargo, firma FROM trabajadores WHERE cedula=?", (cedula,))
    data = cursor.fetchone()
    conn.close()

    if not data:
        return "<h3>Cédula no encontrada</h3><a href='/'>Volver</a>"

    nombre, cargo, firma = data
    if firma:
        return "<h3>Esta cédula ya firmó.</h3><a href='/'>Volver</a>"

    html = firma_page.replace("{{cedula}}", cedula)\
                     .replace("{{nombre}}", nombre)\
                     .replace("{{cargo}}", cargo)
    return render_template_string(html)

@app.route("/guardar", methods=["POST"])
def guardar():
    cedula = request.form["cedula"]
    firma_base64 = request.form["firma"]

    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute("UPDATE trabajadores SET firma=? WHERE cedula=?", (firma_base64, cedula))
    conn.commit()
    conn.close()

    return pagina_gracias

@app.route("/reporte_final")
def reporte_final():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute("""
        SELECT cedula, nombre, cargo, firma
        FROM trabajadores
        WHERE firma IS NOT NULL AND firma != ''
        ORDER BY nombre
    """)
    rows = cursor.fetchall()
    conn.close()

    if not rows:
        return "<h3>No hay firmas registradas aún</h3><a href='/'>Volver</a>"

    os.makedirs("/content/pdfs", exist_ok=True)
    pdf_path = "/content/pdfs/reporte_firmas_final.pdf"

    c = pdfcanvas.Canvas(pdf_path, pagesize=A4)
    width, height = A4

    # ---------- BLOQUE 1: ENCABEZADO ----------
    c.rect(30, height - 110, width - 60, 80)

    if os.path.exists("/content/Registro-de-asistencia-ISMOCOL-SA/logoismocol.png"):
        c.drawImage("/content/Registro-de-asistencia-ISMOCOL-SA/logoismocol.png", 40, height - 100, width=80, height=60)

    c.setFont("Helvetica-BoldOblique", 14)
    texto = "REGISTRO DE ASISTENCIA"
    x = 160
    y = height - 65

    c.drawString(x, y, texto)
    ancho_texto = c.stringWidth(texto, "Helvetica-BoldOblique", 14)
    c.line(x, y - 2, x + ancho_texto, y - 2)    

    c.setFont("Helvetica-Bold", 10)
    c.drawString(420, height - 55, "ICQ-GRAL-F-010")
    c.drawString(420, height - 75, "Revisión 5.")

    # ---------- CASILLAS DE ACTIVIDAD (ENTRE BLOQUE 1 Y 2) ----------
    c.setFont("Helvetica", 8)
    actividades = ["INDUCCION", "ENTRENAMIENTO", "CAPACITACION", "CHARLA", "REUNION", "ACTIVIDAD LUDICA"]

    x = 50
    y_cajas = height - 130  # justo debajo del bloque 1

    for act in actividades:
      c.rect(x, y_cajas, 10, 10)
      c.drawString(x + 14, y_cajas + 1, act)
      x += 85



    # ---------- BLOQUE 2: DATOS DEL FORMATO ----------
    bloque2_top = height - 130
    bloque2_height = 90
    c.rect(30, bloque2_top - bloque2_height, width - 60, bloque2_height)

    c.setFont("Helvetica", 10)

    from datetime import datetime, timedelta

    fecha_colombia = (datetime.utcnow() - timedelta(hours=5)).strftime('%d/%m/%Y')

    campos = [
        ("AREA FRENTE", ""),
        ("FECHA", fecha_colombia),
        ("LUGAR", ""),
        ("DURACION", ""),
        ("FACILITADOR", ""),
        ("FIRMA", ""),
    ]

    x1, x2 = 50, 300
    y_start = bloque2_top - 25
    line_height = 22

    for i in range(0, len(campos), 2):
        campo1, valor1 = campos[i]
        campo2, valor2 = campos[i + 1]
        y = y_start - (i // 2) * line_height

        c.drawString(x1, y, f"{campo1}:")
        c.line(x1 + 80, y - 2, x1 + 220, y - 2)

        c.drawString(x2, y, f"{campo2}:")
        c.line(x2 + 70, y - 2, x2 + 220, y - 2)

        if campo2 == "FECHA":
            c.setFont("Helvetica", 9)
            c.drawString(x2 + 75, y, valor2)
            c.setFont("Helvetica", 10)



    # ---------- TEMAS ----------
    y = y_cajas - 100
    c.setFont("Helvetica", 10)
    c.drawString(50, y, "TEMAS:")
    c.line(100, y - 2, width - 50, y - 2)
    c.line(100, y - 2, width - 50, y - 2)
# Espacio extra para escribir en TEMAS
    y -= 15
    c.line(100, y - 2, width - 50, y - 2)


    # ---------- TEXTO LEGAL ----------
    y -= 90
    texto_legal = (
        "Autorización de tratamiento de información personal: El firmante autoriza a Ismocol SA "
        "para que realice el tratamiento de su información. personal de conformidad con el Manual "
        "de Políticas y Procedimientos para la Protección. de Datos Personales ICA-GRAL-M-05 "
        "Ismocol SA realizará un tratamiento responsable. y seguro de los datos suministrados "
        "conforme las previsiones de la Ley 1581 de 2012 y las normas que la reglamentan. "
        "Manifiesto que he recibido y entendido en todo su alcance el tema tratado y me comprometo "
        "a cumplir con el procedimiento o contenido. de los temas y responsabilidades a mi asignadas. "
        "En constancia firmo."
    )

    c.setFont("Helvetica", 9)
    textobject = c.beginText(40, y)
    for linea in texto_legal.split(". "):
        textobject.textLine(linea.strip() + ".")
    c.drawText(textobject)

    # ---------- ENCABEZADO DE LA LISTA ----------
    y -= 120
    c.setFont("Helvetica-Bold", 9)
    c.drawString(40, y + 18, "No.")
    c.drawString(70, y + 18, "NOMBRE")
    c.drawString(200, y + 18, "CARGO")
    c.drawString(350, y + 18, "CEDULA")
    c.drawString(450, y + 18, "FIRMA")
    c.line(40, y + 15, 560, y + 15)

    # ---------- LISTA DE ASISTENTES (COMPACTA) ----------
    c.setFont("Helvetica", 12)
    contador = 1
    y -= 10   # menos espacio antes de empezar la lista

    for cedula, nombre, cargo, firma in rows:
      if y < 120:
        c.showPage()
        y = height - 80

      c.drawString(40, y, str(contador))
      c.drawString(70, y, nombre[:28])
      c.drawString(200, y, cargo[:28])
      c.drawString(350, y, str(cedula))

      firma_clean = firma.split(",")[1]
      firma_bytes = base64.b64decode(firma_clean)
      img = ImageReader(BytesIO(firma_bytes))

    # Firma un poco más bajita y más pequeña
      c.drawImage(img, 420, y - 8, width=120, height=25, mask='auto')

      y -= 30   # 👈 salto de renglón normal
      contador += 1


    c.save()
    return send_file(pdf_path, mimetype="application/pdf", as_attachment=False)

    


# ---------------- INICIAR ----------------

public_url = ngrok.connect(5000)
print("📱 LINK PARA CELULAR:", public_url)

app.run(host="0.0.0.0", port=5000)

